
name: CI

on:
  push:
    branches: [ "main" ]  # Trigger workflow on push to the main branch
  pull_request:
    branches: [ "main" ]  # Trigger workflow on pull request to the main branch
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
       
      - uses: actions/checkout@v4  # Checkout the repository

      - name: Get Branch
        id: branch
        run: echo "git_branch=${GITHUB_REF#refs/heads/}" 
            echo "echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")""

      - name: Check Branch
        run: echo "${{ env.branch }}" # display branch
      - name: Ensure Docs directory exists
        run: mkdir -p ./Docs  # Create the Docs directory if it doesn't exist

      - name: Upload GitHub Pages artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages  # Name the artifact as github-pages
          path: ./Docs  # Specify the path to the artifact
      - name: Summary 
        run: echo "Hello world" >> $GITHUB_STEP_SUMMARY

  deploy-to-pages:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    needs: build  # This job depends on the build job

    permissions:
      pages: write  # Grant write permissions for pages
      id-token: write  # Grant write permissions for id-token
      contents: read  # Grant read permissions for contents
    environment:
      name: github-pages  # Set the environment name to github-pages
      url: ${{ steps.deployment.outputs.page_url }}  # Use the URL output from the deployment step

    steps:
      - name: Download GitHub Pages artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages  # Specify the name of the artifact to download

      #- name: Configure Pages
        #uses: actions/configure-pages@v4  # Configure GitHub Pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v4  # Deploy the artifact to GitHub Pages
        with:  
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Docs
          publish_branch: gh-pages
          allow_empty_commit: false
          keep_files: false
          force_orphan: false
          enable_jekyll: true
          no_jekyll: false
