
name: CI

on:
  push:
    branches: [ "main" ]  # Trigger workflow on push to the main branch
  pull_request:
    branches: [ "main" ]  # Trigger workflow on pull request to the main branch
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
       
      - uses: actions/checkout@v4  # Checkout the repository

      - name: Get Branch
        id: branch
        run: echo "git_branch=${GITHUB_REF#refs/heads/}" 
            echo "echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")""

      - name: Check Branch
        run: echo "${{ env.branch }}" # display branch
      - name: Ensure Docs directory exists
        run: mkdir -p ./Docs  # Create the Docs directory if it doesn't exist

      - name: Upload GitHub Pages artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages  # Name the artifact as github-pages
          path: ./Docs  # Specify the path to the artifact
      - name: Summary 
        run: cat summary.md >> $GITHUB_STEP_SUMMARY
      - name: Hello World 
        run: echo "hello " >> $GITHUB_STEP_SUMMARY

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          file-path: ./summary.md
          
  deploy-to-pages:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    needs: build  # This job depends on the build job

    permissions:
      pages: write  # Grant write permissions for pages
      id-token: write  # Grant write permissions for id-token
      contents: read  # Grant read permissions for contents

    steps:
      - uses: actions/checkout@v4  # Checkout the repository
      
      - name: Download GitHub Pages artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages  # Specify the name of the artifact to download

      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v2.0.0
        with:
          name: github-pages

